name: background_location_tracker_example
description: Demonstrates how to use the background_location_tracker plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  background_location_tracker:
    path: ../
  flutter:
    sdk: flutter
  flutter_local_notifications: ^5.0.0-nullsafety.1
  permission_handler: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
